USE FeroTmp

SELECT TJ.*, 
	(SELECT PAR.NazivPar FROM Partneri PAR WHERE PAR.ID_Par = (SELECT ULR.ID_Par FROM UlazRobeDetaljnoView ULR WHERE ULR.ID_ULR = (SELECT IZR.ID_ULR FROM IzlazRobe IZR WHERE IZR.ID_IZR = (SELECT ULP.ID_IZR FROM UlazProizvoda ULP WHERE ULP.ID_ULP = (SELECT FS.ID_Ulp FROM FaktureSta FS WHERE FS.ID_FS = TJ.ID_FS))))) AS Dobavljac 
	FROM TmpJanjic TJ 
	ORDER BY TJ.Item 