USE FxFirme
	
SELECT DC.TableName_rv, COUNT(*) FROM DatabaseCompare() DC GROUP BY DC.TableName_rv ORDER BY DC.TableName_rv

--DECLARE @SqlQuery varchar(max);

-- SELECT * FROM FeroApp.INFORMATION_SCHEMA.TABLES ORDER BY TABLE_NAME



/*SELECT (SELECT COUNT(*) FROM FeroApp.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'Proizvodi'), 
	(SELECT COUNT(*) FROM FeroAppFX.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'Proizvodi'), 
	(SELECT COUNT(*) FROM FeroAppTKB.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'Proizvodi'), 
	(SELECT COUNT(*) FROM FeroAppArh2015.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'Proizvodi') */

-- SELECT COUNT(*) FROM FeroApp.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'AsnZag' --ORDER BY ORDINAL_POSITION