USE FeroTmp

--INSERT INTO TmpULR (Vrsta, ID_ULR)
	--SELECT 'ULR', ID_ULR FROM StanjeULR('2015-12-31') WHERE DatumDokumenta <= '2015-12-31' AND (CASE WHEN VrstaOtpisa = 'Komadno' THEN SaldoKolicina ELSE SaldoTezina END) = 0

/*UPDATE TmpULR 
	SET CntIZR = (SELECT COUNT(*) 
				FROM IzlazRobeDetaljnoView 
				WHERE IzlazRobeDetaljnoView.VrstaDokumenta IN('Izdatnica', 'Otpremnica') 
				AND IzlazRobeDetaljnoView.ID_ULR = TmpULR.ID_ULR
				AND (CASE WHEN IzlazRobeDetaljnoView.VrstaOtpisa = 'Komadno' THEN dbo.CalcStanjeIZR(IzlazRobeDetaljnoView.ID_IZR, 0, '2015-12-31') ELSE dbo.CalcStanjeIZR_Kg(IzlazRobeDetaljnoView.ID_IZR, 0, '2015-12-31') END) <> 0)
	WHERE Vrsta = 'ULR'*/

/*UPDATE TmpULR 
	SET CntULP = (SELECT COUNT(*) 
				FROM UlazProizvodaDetaljnoView 
				WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobeDetaljnoView WHERE ID_ULR = TmpULR.ID_ULR AND VrstaDokumenta IN('Izdatnica', 'Otpremnica')) 
				AND (KolicinaPro + VisakPro + OtpadProFaktura - dbo.CalcStanjeProizvoda(ID_ULP, '2015-12-31', 'ULPP')) <> 0)
	WHERE Vrsta = 'ULR'*/

 -- SELECT * FROM TmpULR WHERE (CntIZR > 0 OR CntULP > 0)

 -- SELECT * FROM FaktureDetaljnoView WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))) ORDER BY DatumFakture
 -- SELECT * FROM FaktureDetaljnoView WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) ORDER BY DatumFakture
 -- SELECT * FROM UlazProizvodaKorekcija WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))) ORDER BY DatumKorekcije
 -- SELECT * FROM UlazProizvodaDetaljnoView WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))) ORDER BY DatumDokumenta
 -- SELECT * FROM IzlazRobeKorekcija WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) ORDER BY DatumKorekcije
 -- SELECT * FROM IzlazRobeDetaljnoView WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) AND Parent_IZR_ID IS NOT NULL ORDER BY DatumIzlaza
 -- SELECT * FROM IzlazRobeDetaljnoView WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) AND Parent_IZR_ID IS NULL ORDER BY DatumIzlaza
 -- SELECT * FROM UlazRobeKorekcija WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0) ORDER BY DatumKorekcije
 -- SELECT * FROM VezeDokSta WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)
 -- SELECT * FROM UlazRobeDetaljnoView WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0) ORDER BY DatumDokumenta

 -- DELETE FROM FaktureSta WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))) 
 -- DELETE FROM FaktureSta WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))
 -- DELETE FROM UlazProizvodaKorekcija WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)))
 -- DELETE FROM UlazProizvoda WHERE ID_Ulp IN(SELECT ID_Ulp FROM UlazProizvoda WHERE ID_Izr IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))) 
 -- DELETE FROM IzlazRobeKorekcija WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0))
 -- DELETE FROM IzlazRobe WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) AND Parent_IZR_ID IS NOT NULL
 -- DELETE FROM IzlazRobe WHERE ID_IZR IN(SELECT ID_IZR FROM IzlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)) AND Parent_IZR_ID IS NULL
--  DELETE FROM UlazRobeKorekcija WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)
 -- DELETE FROM VezeDokSta WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)
 -- DELETE FROM UlazRobeOcjenaDobavljaca WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)
 -- DELETE FROM UlazRobe WHERE ID_ULR IN(SELECT ID_ULR FROM TmpULR WHERE CntIZR = 0 AND CntULP = 0)
 -- DELETE FROM VezeDokZag WHERE (SELECT COUNT(*) FROM VezeDokSta WHERE ID_VDZ = VezeDokZag.ID_VDZ) = 0