use FeroApp

SELECT KolicinaPro * TezinaProKom AS Tezina, ID_Pro, KolicinaPro, (SELECT ID_Par FROM FaktureZag WHERE ID_FZ = FaktureSta.ID_FZ) AS ID_Par, VlasnistvoFX, 
	(SELECT YEAR(DatumNarudzbe) FROM NarudzbeZag WHERE ID_NarZ = (SELECT ID_NarZ FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END)))) AS Godina_Nar, 
	(SELECT ID_Pro FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))) AS ID_Pro_Nar, 
	(SELECT OrderNo FROM NarudzbeDetaljnoView WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))) AS OrderNo,
	(SELECT TOP 1 OrderNo FROM NarudzbeDetaljnoView WHERE ID_Par = (SELECT ID_Par FROM FaktureZag WHERE ID_FZ = FaktureSta.ID_FZ) AND ID_Pro = (SELECT ID_Pro FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))) AND YEAR(DatumNarudzbe) = (SELECT YEAR(DatumNarudzbe) FROM NarudzbeZag WHERE ID_NarZ = (SELECT ID_NarZ FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))))) AS OrderNo_Parent,
	(SELECT (CASE WHEN Obrada5 = 1 THEN BrojRN5 WHEN Obrada4 = 1 THEN BrojRN4 WHEN Obrada3 = 1 THEN BrojRN3 WHEN Obrada2 = 1 THEN BrojRN2 WHEN Obrada1 = 1 THEN BrojRN1 ELSE NULL END)) AS RN,
    (SELECT REPLACE(ID_Pro_Kup, '-', '') FROM Proizvodi WHERE ID_Pro = (SELECT ID_Pro FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END)))) AS ID_Pro_Kupac,
    (SELECT NazivPro FROM Proizvodi WHERE ID_Pro = (SELECT ID_Pro FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END)))) AS NazivPro,
    (SELECT TOP 1 PozicijaKupac FROM NarudzbeDetaljnoView WHERE ID_Par = (SELECT ID_Par FROM FaktureZag WHERE ID_FZ = FaktureSta.ID_FZ) AND ID_Pro = (SELECT ID_Pro FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))) AND YEAR(DatumNarudzbe) = (SELECT YEAR(DatumNarudzbe) FROM NarudzbeZag WHERE ID_NarZ = (SELECT ID_NarZ FROM NarudzbeSta WHERE BrojRN = (SELECT (CASE WHEN FaktureSta.Obrada5 = 1 THEN FaktureSta.BrojRN5 WHEN FaktureSta.Obrada4 = 1 THEN FaktureSta.BrojRN4 WHEN FaktureSta.Obrada3 = 1 THEN FaktureSta.BrojRN3 WHEN FaktureSta.Obrada2 = 1 THEN FaktureSta.BrojRN2 WHEN FaktureSta.Obrada1 = 1 THEN FaktureSta.BrojRN1 ELSE NULL END))))) AS Pozicija
    FROM FaktureSta WHERE ID_Ulp IS NOT NULL AND ID_AsnZ = 2 AND KolicinaPro <> 0